services:
  app:
    build: .
    container_name: presence_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "file:./dev.db"
    command: ["npm", "run", "dev"]
